#include "Adherent.h"




void Adherent::emprunterLivre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--125-1--11a75334:16e1d1beb8b:-8000:000000000000086C begin
{
}
// section -64--88--125-1--11a75334:16e1d1beb8b:-8000:000000000000086C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Adherent::rendreLivre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--125-1--11a75334:16e1d1beb8b:-8000:00000000000008A2 begin
{
}
// section -64--88--125-1--11a75334:16e1d1beb8b:-8000:00000000000008A2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
